### ISSUE TITLE
Build Error: 'math ' has not been declared

### ISSUE THREAD

**Issue by vec123** [tahsinkose/sjtu-drone#2]
Hi, i am getting several error when trying to build the package. All of those are along the line of
'math' has not been declared.... or GetSimTime() is unkown and many further variables which are not recognised as they should be. Please help me, I really can't wait to finally get this programm to work and play around with it.

**Comment by tahsinkose** [comment]
The `math` namespace is different for different Gazebo versions. Since Gazebo 8.0+ `ignition::math` is being used, whereas older versions use `gazebo::math`. See [changelog](https://bitbucket.org/osrf/gazebo/src/default/Changelog.md).

Also, it is not always to best option to open an issue when a problem occurs. For instance, this question is already answered in [here](http://answers.gazebosim.org/question/16373/math-has-not-been-declared-gazebo-8-write-plug-in-tutorial/). Anyways, I have updated the code and did it for you :slightly_smiling_face:

**Comment by vec123** [comment]
Being the beginner I am and not knowing a lot about ROS I didn't really figure out how to change gazebo::math to ignition::math. Could you maybe please explain in more detail how I could solve this problem? I also tried deinstalling and reinstalling after reading that you updated the code but nothing changed. The same error still appears. Thank you again!!

**Comment by tahsinkose** [comment]
Please post the specific compilation error that you have encountered during compilation.

**Comment by vec123** [comment]
Ok it worked... thank you. Seemingly I did not have the right gazebo version installed. After doing that and remaking the package everything seemed to work. Thank you!
